#include "dot.h"
#include "chararray.h"

#include <stdlib.h>
#include <stdio.h>
#include <errno.h>

/*
 *@requires atm is a valid pointer, *atm is valid too and *file is writable
 *@assigns nothing
 *@ensures *atm is still valid and lines are added to dot file
*/
void processReduit(automaton const *atm, int const state, FILE * file, char const lettre)
{
    int n=atm->reduit1[state];
    char A=atm->reduit2[state];
    if (lettre == '\n')
    {
        fprintf(file,"Q%d ->[label=\"\\n\",color=blue] %d%c [label=\"(%d,%c)\",shape=plaintext];\n",state,n,A,n,A);
    }
    else fprintf(file,"Q%d ->[label=\"%c\",color=blue] %d%c [label=\"(%d,%c)\",shape=plaintext];\n",state,lettre,n,A,n,A);
    //La convention utilisée pour cet automate est que branchement[i][j] vaut -1 si cette case ne peut pas être atteinte
    if (n == 0)
    {
        if (A=='\n') fprintf(file,"    Q%d ->[label=\"\\n\",color=red] Q%d;\n",state,atm->branchement[state][(int)A]);
        else fprintf(file,"    Q%d ->[label=\"%c\",color=red] Q%d;\n",state,A,atm->branchement[state][(int)A]);
    }
    else
    {
        for (int i = 0; i < atm->nbStates; i++)
        {
            if (atm->branchement[i][(int)A] != -1 && i != state && atm->branchement[i][(int)A] != i && atm->branchement[i][(int)A] != state)
            {
                if (A=='\n') fprintf(file,"    Q%d ->[label=\"\\n\",color=red] Q%d;\n",i,atm->branchement[i][(int)A]);
                else fprintf(file,"    Q%d ->[label=\"%c\",color=red] Q%d;\n",i,A,atm->branchement[i][(int)A]);
                break;
            }
        }
    }
}

void processDot(automaton const * atm,char const* filename)
{
    char *filenameWithoutExtension = substring(filename,0,size(filename)-4);
    char *filenameExt = concatenate(filenameWithoutExtension,".dot");
    FILE *fileDot = fopen(filenameExt,"w");
    if (!fileDot)
    {
        fprintf(stderr,"File \"%s\" cannot be opened (error code %d).\n",filenameExt,errno);
        fprintf(stderr,"No DOT file will be produced.\n");
        free(filenameWithoutExtension);
        filenameWithoutExtension = NULL;
        free(filenameExt);
        filenameExt=NULL;
    }
    else
    {
        fprintf(fileDot,"//DOT representation of automaton %s\n",filenameWithoutExtension);
        fprintf(fileDot,"//This file has been automatically generated by \"automaton\".\n");
        fprintf(fileDot,"//This automaton has %d states.\n",atm->nbStates);
        fprintf(fileDot,"//If a character is not there, it means that it cannot be recognized by this automaton.\n");
        fprintf(fileDot,"//You can use Ajax/Graphviz to read this file into a schematics of this automaton.\n");
        fprintf(fileDot,"digraph %s {\n",filenameWithoutExtension);
        free(filenameWithoutExtension);
        filenameWithoutExtension = NULL;
        fprintf(fileDot,"    init [style=invis]->[label=\"start\"] Q0;\n");
        //Comme *atm est valide, atm->actions[i][j] ne contient que 0, 1, 2 ou 3
        for (int i = 0; i < atm->nbStates; i++)
        {
            for (int j = 0; j < 128; j++)
            {
                switch (atm->actions[i][j])
                {
                case 1://Accepte
                    fprintf(fileDot,"    ");
                    if ((char)j == '\n')
                    {
                        fprintf(fileDot,"Q%d ->[label=\"\\n\",color=green] Act [label=\"Accepted\",shape=plaintext];\n",i);
                    }
                    else fprintf(fileDot,"Q%d ->[label=\"%c\",color=green] Act [label=\"Accepted\",shape=plaintext];\n",i,(char)j);
                    break;
                case 2://Décale
                    fprintf(fileDot,"    ");
                    if ((char)j == '\n')
                    {
                        fprintf(fileDot,"Q%d ->[label=\"\\n\",color=black] Q%d;\n",i,atm->decale[i][j]);
                    }
                    else fprintf(fileDot,"Q%d ->[label=\"%c\",color=black] Q%d;\n",i,(char)j,atm->decale[i][j]);
                    break;
                case 3://Réduit
                    fprintf(fileDot,"    ");
                    processReduit(atm,i,fileDot,(char)j);
                    break;
                default://Action rejette donc on ne fait rien
                    break;
                }
            }
        }
        fprintf(fileDot,"}\n");
        fclose(fileDot);
        printf("To view the DOT file, use the command \"cat %s\".\n",filenameExt);
        free(filenameExt);
        filenameExt=NULL;
    }
}